id: "base_hpo"
base_config: 'base'
hpo:
  num_samples: 50
  cpu_per_trial: 2
  gpu_per_trial: 0.15
  hpo_algorithm:
    name: 'SkOptSearch'
    params:
      mode: 'max'
data:
  params:
    batch_size: ['uniform', [50, 512]]
model:
  params:
    pretrained: ['choice', [['', 'true']]]
optimizer:
  name: ['choice', [['Adam', 'RAdam', 'Ranger']]]
  params:
    lr: ['loguniform', [0.0001, 0.01]]
    weight_decay: ['loguniform', [0.000001, 0.001]]