id: ""
base_config: 'labelled'
env:
  result_dir: "results/labelled_hpo/hpo_outputs/run_experiment_2021-11-20_19-56-42/run_experiment_{'result_dir': 'results', 'random_seed': 0, 'epochs': 50, 'save_preds': False}_8b7edf0d_42_base_config=labelled,nam_2021-11-20_20-20-31"
  save_preds: true
data:
  params:
    data_parts: ['unlabelled']